/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fff0ef",
        "crimson-hover": "#A11425",
        "surface-tint": "#b9192e",
        "secondary-fixed": "#ffdea5",
        "on-primary": "#ffffff",
        "surface-dim": "#f0d3d2",
        "inverse-surface": "#3e2c2b",
        "on-background": "#271817",
        "tertiary-container": "#006880",
        "tertiary-fixed-dim": "#86d1ec",
        "background": "#fff8f7",
        "text-charcoal": "#1A1A1A",
        "on-primary-fixed-variant": "#92001d",
        "error": "#ba1a1a",
        "border-subtle": "#F0EFEA",
        "tertiary": "#004e61",
        "crimson-subtle": "#FDF2F3",
        "on-surface-variant": "#5b403f",
        "on-tertiary-fixed": "#001f28",
        "surface-variant": "#f9dcda",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "surface-container-highest": "#f9dcda",
        "tertiary-fixed": "#b6eaff",
        "on-error-container": "#93000a",
        "text-muted": "#6B7280",
        "primary": "#93001d",
        "on-secondary": "#ffffff",
        "champagne-gold": "#C5A059",
        "on-primary-container": "#ffcdcc",
        "on-surface": "#271817",
        "outline-variant": "#e3bebc",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad8",
        "inverse-on-surface": "#ffedeb",
        "secondary": "#775a19",
        "border-hairline": "#E5E5E5",
        "on-tertiary-fixed-variant": "#004e60",
        "error-container": "#ffdad6",
        "whatsapp-green": "#25D366",
        "primary-fixed-dim": "#ffb3b1",
        "surface-container-high": "#ffe2e0",
        "surface-bright": "#fff8f7",
        "surface-container-lowest": "#ffffff",
        "canvas-cream": "#FAF9F6",
        "outline": "#8f6f6e",
        "gold-light": "#F7F3E9",
        "primary-container": "#ba1a2e",
        "on-primary-fixed": "#410007",
        "inverse-primary": "#ffb3b1",
        "surface-container": "#ffe9e8",
        "on-tertiary-container": "#9ce4ff",
        "on-secondary-container": "#785a1a",
        "secondary-container": "#fed488",
        "surface-card": "#FFFFFF",
        "crimson-primary": "#BA1A2E",
        "surface": "#fff8f7",
        "on-secondary-fixed-variant": "#5d4201",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "3rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-2xl": "4rem",
        "margin-mobile": "1.25rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Playfair Display'", "serif"],
        "editorial-quote": ["'Playfair Display'", "serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "label-xs": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Playfair Display'", "serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "serif": ["'Playfair Display'", "serif"],
        "sans": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.06em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "editorial-quote": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
